### ISSUE TITLE
Question about onion routing and friend request

### ISSUE THREAD

**Issue by iacore** [TokTok/tox-spec#83]
If I understand the protocol correctly, friend requests have onion routing enabled. A friend request can also have a piece of text attached to it.

So like, can't we enable full onion routing with this design? That is, to send every message with onion routing.

**Comment by nurupo** [comment]
Technically you could onion-route arbitrary data via DHT, but it makes no sense for Tox to do so. Tox aims to establish direct connection between the recipient and the sender to allow low-latency audio/video conferencing, high-bandwidth file transfers, etc. Anonymity is not a goal of Tox. See https://toktok.ltd/spec.html#non-goals

Onion routing is currently used to solve a privacy issue with friend finding, because without the friend finding being onion-routed, one could easily learn Tox IDs of all friends any Tox ID has in their friend list. There are some proposals that promise private friend finding without needing the onion routing, so in the future the onion routing might not even be a part of Tox.

**Comment by iacore** [comment]
> There are some proposals that promise private friend finding without needing the onion routing, so in the future the onion routing might not even be a part of Tox.

Can you point me to such proposals?

**Comment by robinlinden** [comment]
> Can you point me to such proposals?

https://github.com/zugz/tox-DHTAnnouncements/blob/master/DHTAnnouncements.md

**Comment by iacore** [comment]
> > Can you point me to such proposals?
> 
> https://github.com/zugz/tox-DHTAnnouncements/blob/master/DHTAnnouncements.md

if i run a service that relies on the add-friend message to decide whether a connection gets accepted, it will no longer work. should i just use I2P or Veilid for my service then?
